### ISSUE TITLE
Migrate from pylemmy to plemmy

### ISSUE THREAD

**Issue by emilymclean** [origma/LemmyModBot#1]
Currently, the entire project uses pylemmy as the library used to interact with a given lemmy instance. This library provides a nice API, but lacks many of the features I've had to make up for with in-project extensions. Plemmy implements all these APIs, and more. In addition, pylemmy appears to have broken dependencies making it difficult to install new libraries, as they break the install.

The old pylemmy code and extensions should be cleared out and refactored to instead use plemmy.

**Comment by IanOxborrow** [comment]
closes issue #1
